# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccswitch < Formula
  desc "Switch between multiple Claude Code accounts in <100 ms"
  homepage "https://github.com/nhtera/ccswitch"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nhtera/ccswitch/releases/download/v1.0.0/ccswitch_1.0.0_darwin_amd64.tar.gz"
      sha256 "1073300153b4a2058645a21d91f6e3ec692525c40b977e87e198ce219545135b"

      define_method(:install) do
        bin.install "ccswitch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nhtera/ccswitch/releases/download/v1.0.0/ccswitch_1.0.0_darwin_arm64.tar.gz"
      sha256 "b9b4a8a4898cdb6886134ff0d122aec3265f9ac090610a4d747b6ede9c4cd983"

      define_method(:install) do
        bin.install "ccswitch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nhtera/ccswitch/releases/download/v1.0.0/ccswitch_1.0.0_linux_amd64.tar.gz"
      sha256 "15bef07e114ff082fd4c18ab307904ee79a7b9723bed73303ce990e942ea5fb5"
      define_method(:install) do
        bin.install "ccswitch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nhtera/ccswitch/releases/download/v1.0.0/ccswitch_1.0.0_linux_arm64.tar.gz"
      sha256 "dcdb7024796241cc970181b7198fda0db5d7c4cdc5186cf2e7ecae70f11fb183"
      define_method(:install) do
        bin.install "ccswitch"
      end
    end
  end

  test do
    system "#{bin}/ccswitch", "version"
  end
end
