# Generated by scripts/gen-homebrew-formula.sh from the signed release manifest.
# Do not edit by hand — regenerate for each release.
class Oximux < Formula
  desc "Scriptable client and host for OxiMux agent sessions"
  homepage "https://github.com/nhtera/OxiMux"
  version "0.1.15"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/nhtera/OxiMux/releases/download/v0.1.15/oximux-0.1.15-aarch64-apple-darwin.tar.gz"
      sha256 "57c6011b426c192fa7b3d5340eb2cd414f14b23ff16dc758389144db977fbc81"
    end
    on_intel do
      url "https://github.com/nhtera/OxiMux/releases/download/v0.1.15/oximux-0.1.15-x86_64-apple-darwin.tar.gz"
      sha256 "1721cc1f50a5e709b06f75f953bf05ec6e02dde6c026bd923ba63e95000eb36a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nhtera/OxiMux/releases/download/v0.1.15/oximux-0.1.15-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "c753508ac2c6f0a338a19e9a4824ed1a23e3f9046e0dfe03681a885d057495c7"
    end
    on_arm do
      url "https://github.com/nhtera/OxiMux/releases/download/v0.1.15/oximux-0.1.15-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "ade8b7849114038b346865ab00b4df5e333277af80cc8efd0583a43f970ebd12"
    end
  end

  def install
    # Both, always. The CLI and the relay speak a handshake versioned in
    # lockstep, so installing one without the other yields an installation
    # that cannot talk to itself.
    bin.install "oximux"
    bin.install "oximux-relay"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/oximux version")
  end
end
