# Generated by scripts/gen-homebrew-formula.sh from the signed release manifest.
# Do not edit by hand — regenerate for each release.
class Oximux < Formula
  desc "Scriptable client and host for OxiMux agent sessions"
  homepage "https://github.com/nhtera/OxiMux"
  version "0.1.32"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/nhtera/OxiMux/releases/download/v0.1.32/oximux-0.1.32-aarch64-apple-darwin.tar.gz"
      sha256 "282965b872850f63d03da36cbef6e4283d301d992afd1557aa6a7efedb46ddb7"
    end
    on_intel do
      url "https://github.com/nhtera/OxiMux/releases/download/v0.1.32/oximux-0.1.32-x86_64-apple-darwin.tar.gz"
      sha256 "648c66f2631717e408fa4bc0f22f382985a006b020bd121706cf8da6ec84e202"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nhtera/OxiMux/releases/download/v0.1.32/oximux-0.1.32-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "31e8e7a57f3f8269bf39b642e997453d1e1a4f95f8c163448452f308289ae415"
    end
    on_arm do
      url "https://github.com/nhtera/OxiMux/releases/download/v0.1.32/oximux-0.1.32-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "55d998896a2fa8af0bc79bb3bd023b63c7a4d76fb0e73ee69c4d4200c1d424ee"
    end
  end

  def install
    # Both, always. The CLI and the relay speak a handshake versioned in
    # lockstep, so installing one without the other yields an installation
    # that cannot talk to itself.
    bin.install "oximux"
    bin.install "oximux-relay"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/oximux version")
  end
end
