# Generated by scripts/gen-homebrew-formula.sh from the signed release manifest.
# Do not edit by hand — regenerate for each release.
class Oximux < Formula
  desc "Scriptable client and host for OxiMux agent sessions"
  homepage "https://github.com/nhtera/OxiMux"
  version "0.1.7"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/nhtera/OxiMux/releases/download/v0.1.7/oximux-0.1.7-aarch64-apple-darwin.tar.gz"
      sha256 "f717625358a74474abceaf7e355974093ab6513f78d8755ab5dede0b99f8b1e1"
    end
    on_intel do
      url "https://github.com/nhtera/OxiMux/releases/download/v0.1.7/oximux-0.1.7-x86_64-apple-darwin.tar.gz"
      sha256 "8bdd28a4f46f9d23cc131804729cf66270102d3ba3172c892f2488ce15561b91"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nhtera/OxiMux/releases/download/v0.1.7/oximux-0.1.7-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "221412889280a4203e2996208ce45a54d07ed1c4a1fdc0cd8d30a6aceb1cb0c1"
    end
    on_arm do
      url "https://github.com/nhtera/OxiMux/releases/download/v0.1.7/oximux-0.1.7-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "e190754013f033da6db3f6982270fc0f2fb96fabde7dfbce67636156459a9e3f"
    end
  end

  def install
    # Both, always. The CLI and the relay speak a handshake versioned in
    # lockstep, so installing one without the other yields an installation
    # that cannot talk to itself.
    bin.install "oximux"
    bin.install "oximux-relay"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/oximux version")
  end
end
