# This file was generated by GoReleaser. DO NOT EDIT.
cask "sonde" do
  version "1.3.1"

  on_macos do
    on_arm do
      sha256 "28675ff3bf256022feb2573944f82342b56559c4d94147510232bf3da8f1ae85"
      url "https://github.com/nhtera/Sonde/releases/download/v#{version}/sonde_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c733e244cfec03ad256543f2cd0e170fff3cc507a7c7cfebe97609a91e66a78b"
      url "https://github.com/nhtera/Sonde/releases/download/v#{version}/sonde_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "fd19d1bdc267dd20c23e48af67f61dda79b2b72e5dbf0afad5b9a4a483be49f1"
      url "https://github.com/nhtera/Sonde/releases/download/v#{version}/sonde_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "29f40ae6c4add02c1560110f783c8142bf469b67144c5f047053ad63c2a8ff6d"
      url "https://github.com/nhtera/Sonde/releases/download/v#{version}/sonde_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sonde"
  desc "A single-binary HTTP file runner and testing CLI, LSP and VS Code extension"
  homepage "https://github.com/nhtera/sonde"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sonde"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sonde"]
    end
  end

  # No zap stanza required
end
