# This file was generated by GoReleaser. DO NOT EDIT.
cask "sonde" do
  version "1.4.1"

  on_macos do
    on_arm do
      sha256 "1cd46d1982d7e3c495249a4e082458fe6676b5c2baa0c631adc2732e49587904"
      url "https://github.com/nhtera/Sonde/releases/download/v#{version}/sonde_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b2b2232bcfc1077e2d8c9c021a31385ce2c2c965c926b658a5fb548bd1c9b8a1"
      url "https://github.com/nhtera/Sonde/releases/download/v#{version}/sonde_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "cbb1a62f54e0861edf79457b4dff35ba53c811ba906201fcbd979112ae126008"
      url "https://github.com/nhtera/Sonde/releases/download/v#{version}/sonde_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "65ea716cab852af910c82634b4a4e8749bf904291ace3beef046676a18be7f52"
      url "https://github.com/nhtera/Sonde/releases/download/v#{version}/sonde_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sonde"
  desc "A single-binary HTTP file runner and testing CLI, LSP and VS Code extension"
  homepage "https://github.com/nhtera/sonde"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sonde"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sonde"]
    end
  end

  # No zap stanza required
end
