# This file was generated by GoReleaser. DO NOT EDIT.
cask "sonde" do
  version "1.0.0-rc.1"

  on_macos do
    on_arm do
      sha256 "654dec8c0f6614c4596cf0dfcc9bdca6953e48503b307664939c010f72c8780d"
      url "https://github.com/nhtera/Sonde/releases/download/v#{version}/sonde_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "13fc95809441dac313eb47bd71a9bd2c49609cfa3607275c31d2e2b512dc0f0f"
      url "https://github.com/nhtera/Sonde/releases/download/v#{version}/sonde_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d9f35d805294a186b9ad331bb1212cbcf973f2c1c4226481377ece9238adbd98"
      url "https://github.com/nhtera/Sonde/releases/download/v#{version}/sonde_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6d65fed233750c6acb0932837ca5aa1e8ffde2b3fd7889e2049252dd05c96d0c"
      url "https://github.com/nhtera/Sonde/releases/download/v#{version}/sonde_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sonde"
  desc "A single-binary HTTP file runner and testing CLI, LSP and VS Code extension"
  homepage "https://github.com/nhtera/sonde"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sonde"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sonde"]
    end
  end

  # No zap stanza required
end
