# This file was generated by GoReleaser. DO NOT EDIT.
cask "tuzy" do
  version "0.9.6"

  on_macos do
    on_arm do
      sha256 "e4f43e83d6c5286bea106a8be19beac243ee2796ec76f9a653f9b3f6464c5e43"
      url "https://github.com/nhtera/tuzy/releases/download/v#{version}/tuzy_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "208ac3434be3d46448bf71cd9664077ca966154a67222ea4aa19280225536d1e"
      url "https://github.com/nhtera/tuzy/releases/download/v#{version}/tuzy_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8118df91536d5ec0ecaad9456fd1d0e6a4e520abcf9acc4789c595f0cd153732"
      url "https://github.com/nhtera/tuzy/releases/download/v#{version}/tuzy_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b6df00186296ed808907595a720b407542f351f4b12a111a903f8f0715220a99"
      url "https://github.com/nhtera/tuzy/releases/download/v#{version}/tuzy_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tuzy"
  desc "Expose localhost at a stable https://<name>.tuzy.dev URL"
  homepage "https://tuzy.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tuzy"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tuzy"]
    end
  end

  # No zap stanza required
end
