# This file was generated by GoReleaser. DO NOT EDIT.
cask "tuzy" do
  version "0.9.3"

  on_macos do
    on_arm do
      sha256 "550bcf6640c711696694a0d34fa65bb28968a022dd23655ccc0c830ee8b12029"
      url "https://github.com/nhtera/tuzy/releases/download/v#{version}/tuzy_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1e4c0e5a77f1d33ddb98776b396a3ae383c37f2c605cdc9bab95279b6cd2aee2"
      url "https://github.com/nhtera/tuzy/releases/download/v#{version}/tuzy_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "15fcd45072837e89a7ed19fba06834afbf2ad347ecb0750ec2210c475807c87e"
      url "https://github.com/nhtera/tuzy/releases/download/v#{version}/tuzy_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "581ee91ad521c1d6a49712b581e9c72f044f63d68f086fcc9e302cd9e3c0550f"
      url "https://github.com/nhtera/tuzy/releases/download/v#{version}/tuzy_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tuzy"
  desc "Expose localhost at a stable https://<name>.tuzy.dev URL"
  homepage "https://tuzy.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tuzy"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tuzy"]
    end
  end

  # No zap stanza required
end
