# This file was generated by GoReleaser. DO NOT EDIT.
cask "tuzy" do
  version "0.9.2"

  on_macos do
    on_arm do
      sha256 "2e6d4331e3eb94937be2c4c3da9cbae3882d1b94b7dd83b474979af8b233fef4"
      url "https://github.com/nhtera/tuzy/releases/download/v#{version}/tuzy_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c412d584967ab795a36e3b23df704239fd1112b4b7f05d359cc4d1c73e4f98a4"
      url "https://github.com/nhtera/tuzy/releases/download/v#{version}/tuzy_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6e5a69e5ba037f58ab9bd1d12144c20da5066d1aa4ce20cf85a023a40d3013b8"
      url "https://github.com/nhtera/tuzy/releases/download/v#{version}/tuzy_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "064285d0cd921a2f099eeab0e4f33f4009132454b45d61b29a78bdf5f9c68c79"
      url "https://github.com/nhtera/tuzy/releases/download/v#{version}/tuzy_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tuzy"
  desc "Expose localhost at a stable https://<name>.tuzy.dev URL"
  homepage "https://tuzy.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tuzy"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tuzy"]
    end
  end

  # No zap stanza required
end
